### ISSUE TITLE
standup sandbox deployment

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#13]
@ameukam started this here https://github.com/kubernetes/k8s.io/pull/3318

We still need:
- Loadbalancer
- NEGs
- Cloud Run deployment of the image from this repo (at least for the initial setup)

The infra configs should all live in https://github.com/kubernetes/k8s.io, but that issue tracker is noisier 🙃

**Comment by ameukam** [comment]
xRef: https://github.com/kubernetes/k8s.io/issues/3317

**Comment by BenTheElder** [comment]
Discussed some more 1:1 with arnaud and in the SIG meeting, tentatively we should split this into two deployments:

1. registry-sandbox.k8s.io where we will do active development
2. registry.k8s.io where we will enable a stable version that *only* does the redirect so we can look to shift traffic to the new FQDN

Later we can update registry.k8s.io with all the mirror goodness, when we're ready and registry-sandbox.k8s.io is well tested.

Prior to 2) we're testing registry-sandbox.k8s.io which is already ~stood up, to get some feel for if there's any reason to expect issues with the simple redirect deployment.

**Comment by hh** [comment]
@BobyMCbobs do you and I have access to what is needed for registry-sandbox work?

**Comment by BenTheElder** [comment]
So we actually have a sandbox deployment running now.

But this should be auto-deployed by automation rather than humans, right now it is deployed by Arnaud.

**Comment by BenTheElder** [comment]
And we've since stoodup a "production" deployment which we'll pin to the tagged redirect only image we published today.

**Comment by BenTheElder** [comment]
thoroughly stoodup, see also #24, #55
