### ISSUE TITLE
Stress of registry-sandbox.k8s.io

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/oci-proxy#16]
oci-proxy is currently deployed over the 2 GCP regions: `us-central1` and `us-west1`. We should do some stress tests to build confidence on what we are building and also ensure we can handle `k8s.gcr.io` traffic. 

We should probably ask to GCR team some outdated metrics. 

/sig k8s-infra
/priority important-longterm

**Comment by BobyMCbobs** [comment]
# Background
![image](https://user-images.githubusercontent.com/8588826/158718788-6fb53247-b0f9-435e-84de-6a052fe4e039.png)

Production Kubernetes artifacts currently serve ~60,000,000 requests every day.

# Results
Ran some stress testing against the current registry.k8s.io and the results look pretty good.
The tests were not following redirection and only hitting https://registry.k8s.io/v2/

## 10,000 requests in 30s
![image](https://user-images.githubusercontent.com/8588826/158718989-af8e307f-00d0-43bc-a4db-4240d47e3a13.png)

## 100,00,000 requests in 30s

![image](https://user-images.githubusercontent.com/8588826/158719062-3227a54d-8b93-438a-9b3c-b794895a59cd.png)

## 100,000,000 requests in 60s

![image](https://user-images.githubusercontent.com/8588826/158719098-a1055796-838e-402f-b825-49138c289c51.png)

## Thoughts
Throughout the testing, the service was still accessible and did not appear to have any issues even at 100,000,000 requests per minute.
Given 100,000,000 per-minute running fine and Kubernetes artifacts receiving only 60,000,000 requests per-day, I think that it appears stable

**Comment by dims** [comment]
that's great news @BobyMCbobs

**Comment by hh** [comment]
Thanks @BobyMCbobs ! Great work!

**Comment by aojea** [comment]
impressive, 

now, if we want to be paranoid https://groups.google.com/g/golang-nuts/c/MFZd6b8zQTQ/m/ISD96eyXtD4J  :smile:

**Comment by ameukam** [comment]
@BobyMCbobs is it possible to disclose/document somewhere how this is was done ? (may be https://git.k8s.io/k8s.io/registry.k8s.io ?). Could be really useful if someone else want to re-do it.

**Comment by BobyMCbobs** [comment]
@ameukam, of course. I'll get back to you on that

**Comment by hh** [comment]
Do we want to stress test anymore or can we close this ticket.

**Comment by dims** [comment]
@hh we can close this out

**Comment by BenTheElder** [comment]
Thanks folks!
