### ISSUE TITLE
determine if redirector needs to be AWS-region aware

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#22]
We have two scenarios still on the table for handing off traffic to AWS for AWS clients:

1. We route to cloudfront + s3 or ecr or otherwise some other endpoint that is global and handles serving regional copies internally.

2. We ourselves have regional data storage (e.g. an s3 bucket per continent, region ...) and we need to perform region mapping ourselves before redirecting.

Both of these should be doable in the redirect service, it's mostly a matter of what makes the most sense on the AWS architecture side from a cost perspective. Both have been discussed but we haven't settled on which we'll provide.

Once we know this, we know what the redirection logic needs to look like in the redirector.
Parsing the AWS data is very easy, but the implementation and optimization will look different depending on if we need to detect regions or not.

/assign @jaypipes 

I have a branch locally with benchmarks for 1) that I can easily clean up and turn into 1) or 2), but they look fairly different and I'd like to wait until we know this first.

**Comment by ameukam** [comment]
cc @jaypipes @dims

**Comment by BenTheElder** [comment]
Adding: k8s.gcr.io currently handles mapping to {us,eu,asia}.gcr.io/$actual-registry*, so the redirector uses approach 1) today. I think approach 2) looks quite doable for us though (we will need to push to each and then match region IPs https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html in the redirector), I'm not sure if this is better cost wise than e.g. cloudfront + s3.

* The GCP version of this we have today is a multi-regional GCS/GCR in us,eu,asia, with a frontend routing to the appropriate mutli-regional copy, but this is handled transparently for the project specially, our tools are relatively unaware of this. This is just because that is what the google teams setup, I am clarifying this just for context.

Hopefully one of the AWS experts can recommend which is best for cost, we should have a workload dominated by downloads.

**Comment by jaypipes** [comment]
ref: https://github.com/kubernetes-sigs/oci-proxy/issues/20#issuecomment-1077629290

**Comment by hh** [comment]
> The k8s.gcr.io bucket is public read, should be able to list and collect reported sizes. I think the right call to gsutil ls would even work + summing the results. @BenTheElder 
From https://kubernetes.slack.com/archives/CCK68P2Q2/p1648159238576869?thread_ts=1648085463.736569&cid=CCK68P2Q2

I'll take on generating this via gustil or go. Do we have a list of buckets used by k8s.gcr.io?

**Comment by ameukam** [comment]
> * The GCP version of this we have today is a multi-regional GCS/GCR in us,eu,asia

To be more specific, `k8s.gcr.io` do the mapping to 3 [mutli-regions](https://cloud.google.com/storage/docs/locations#location-mr) buckets and the image layers are replicated between them :

| Bucket name | Total Size | Object  total count* |
| -------- | -------- | -------- |
| `gs://asia.artifacts.k8s-artifacts-prod.appspot.com`     | 1.07 TB  |  93875   |
| `gs://eu.artifacts.k8s-artifacts-prod.appspot.com`     | 1.07 TB  |  93875   |
| `gs://us.artifacts.k8s-artifacts-prod.appspot.com`     | 1.07 TB  |  93875   |

(found the list in https://github.com/kubernetes/k8s.io/blob/main/images/public-log-asn-matcher/buckets.txt)

*Object total count: From https://kubernetes.slack.com/archives/CCK68P2Q2/p1648172955716699?thread_ts=1648085463.736569&cid=CCK68P2Q2

**Comment by BenTheElder** [comment]
It's also probably worth noting that the bulk of those images are likely not often requested, since we continue to host e.g. the very oldest Kubernetes releases that hopefully few are using today :-)

**Comment by dims** [comment]
@jaypipes @hh is this info enough for you?

**Comment by hh** [comment]
I believe so. @jaypipes ?

**Comment by jaypipes** [comment]
> @jaypipes @hh is this info enough for you?

yup.

**Comment by BenTheElder** [comment]
per the call we are doing 2) with a mapping from regions to the nearest bucket, we'll have a bucket in the top N regions.

I've taken the action item to update the redirector to handle this, we also have related items to have image promotion support pushing to these buckets and to figure out what regions to use.

we should move region selection to a new issue. s3 bucket pushing also will have an issue in the image promoter repo.
