### ISSUE TITLE
integration testing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#23]
We should perform an integration test in presubmit. As any additional code complexity is added and we start to roll out registry.k8s.io to projects, it is very important that we test thoroughly, and unit testing alone will not be sufficient.

We should start by having a tool like crane pull an image through a locally running copy of archeio in an integration test target, and adding this to CI.

**Comment by BenTheElder** [comment]
See also https://github.com/kubernetes-sigs/oci-proxy/issues/24 for full e2e testing post-merge.

**Comment by ameukam** [comment]
Ref: https://github.com/kubernetes/k8s.io/issues/3411

**Comment by BenTheElder** [comment]
done in #47
