### ISSUE TITLE
primary upstream backend should be overridable with runtime config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#26]
We should add an environment variable to allow override k8s.gcr.io. This could be useful in testing, and importantly it will allow us to potentially move to some new *.gcr.io as the upstream if we ever manage to update k8s.gcr.io to point to our redirector, which will still be backed by the registries behind k8s.gcr.io in part.

**Comment by ameukam** [comment]
/sig k8s-infra

Ref: https://github.com/kubernetes/k8s.io/issues/3411
