### ISSUE TITLE
Add `preset-use-new-registry` to various jobs

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes-sigs/oci-proxy#29]
In order to add some production load testing on the registry.k8s.io redirection, a request from @dims is to add the label `preset-use-new-registry=true` so that some e2e tests that pull images can pull through the new registry

ref: https://kubernetes.slack.com/archives/CCK68P2Q2/p1647896105383489

**Comment by hh** [comment]
It looks like we need to add the label accord to the pattern lied down by this PR: https://github.com/kubernetes/test-infra/pull/25608/files


To roughly 272 `kubekins-e2e` jobs that end up using **kube-up.sh**

https://cs.k8s.io/?q=kubekins-e2e&i=nope&files=config%2Fjobs&excludeFiles=&repos=kubernetes/test-infra

@dims / @ameukam Caleb will do all these in a single PR unless you prefer something else.

**Comment by dims** [comment]
@hh let's target them in some smaller batches. let's try say the sig-release informing first. then sig-release blocking.

**Comment by BobyMCbobs** [comment]
@hh and I were unsure about which of the [kubekins-e2e jobs in _config/jobs/kubernetes/sig-testing_](https://cs.k8s.io/?q=kubekins-e2e&i=nope&files=config%2Fjobs%2Fkubernetes%2Fsig-testing&excludeFiles=&repos=) need to be modified. Any thoughts, @dims?

**Comment by dims** [comment]
@BobyMCbobs probably nothing there. you can look for `scenario=kubernetes_e2e` you will see 2 of them in that sub-tree. but both are "local" deployment which means they run local-up-cluster.sh and NOT the kube-up scripts.

**Comment by dims** [comment]
@BobyMCbobs looks like we are missing pieces of information floating about ... Let me recap!

```
For preparing a set of things to change:
- work on ONE batch at a time (pick a test-grid board for example release blocking)

- pick a CI job

- look at a last green run in test grid
  Example: https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd
           https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1506360117325467648

- click on Artifacts link in prow
  Example: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1506360117325467648/

- see if you can find images-containerd.log under the control node logs and the worker logs 
  Example: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1506360117325467648/artifacts/bootstrap-e2e-master/
           https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1506360117325467648/artifacts/bootstrap-e2e-minion-group-1wzp/

- Make sure this is NOT a kind based job. kind jobs usually have a kind-version.txt under artifact/logs and the images are in a images.log)

 If you get this far, this is a job you can set the preset for registry for.


After a PR merges in test-infra:
- Go back to images-containerd.json and ensure that the majority of the images are pulled from registry.k8s.io

Other notes:

- Make changes ONLY in master, do not change any previous releases ( https://kubernetes.slack.com/archives/CCK68P2Q2/p1647945052234489 )
- Look for `scenario=kubernetes_e2e` also see when it is not applicable ( https://github.com/kubernetes-sigs/oci-proxy/issues/29#issuecomment-1075083489 )
- Don't touch CAPI based jobs (it will fail the tests above as well) ( https://github.com/kubernetes/test-infra/pull/25717#issuecomment-1074773714 )

```

**Comment by hh** [comment]
Should images-containerd.json still contain the updated image pull locations? @BenTheElder noted that they might not be in the logs, even with logs turned up.

https://github.com/kubernetes-sigs/kind/pull/2688#issuecomment-1075460964

**Comment by dims** [comment]
@hh if you use the preset, you will see the new registry in the images-containerd.json. 

For places where we edit the containerd.toml to add a mirror, that will NOT have the registry.k8s.io in images-containerd.json.

**Comment by hh** [comment]
Hold off for now. There is enough traffic. Waiting for 1.25 (add label)

**Comment by dims** [comment]
we can close this as well. if we need to, we can revive it.
