### ISSUE TITLE
drop registry v1 support

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#34]
This is pointless code bloat at this point apparently, GCR doesn't even serve it and it's unlikely clients were trying to use it / it doesn't support multi-arch images so the past many k8s releases probably would not really work through it ...

ref: https://github.com/kubernetes-sigs/oci-proxy/pull/28#discussion_r831571816

should be a clean, simple PR. we can do further refactors in the future.

/help
/good-first-issue

**Comment by ameukam** [comment]
FYI [GCR ](https://gcr.io) is OCI compliant and respect the Image distribution spec: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pull=

**Comment by BenTheElder** [comment]
Yeah, IIRC v1 predates OCI spec and comes purely from docker/docker inc. We should be safe to drop it, it's a hold over from Tim's prototype which constitutes most of the code we have currently.
