### ISSUE TITLE
determine which AWS regions should serve the image layers

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/oci-proxy#38]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/3411
  
Follow up of:
  - #22 
  
Determine if we should push the image layers to all the AWS regions or pick the regions where we want to push them.
List of AWS S3 regions: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by ameukam** [comment]
/kind feature
/sig k8s-infra
/sig release
/area release-eng
/area artifacts
/milestone v1.24

/assign @BenTheElder @jaypipes 
cc @BobyMCbobs @dims 

cc @kubernetes-sigs/release-engineering

**Comment by BenTheElder** [comment]
> Also if we don't push the image layers to all the AWS regions how de we maintain the mapping between network regions and S3 regions ?

Probably by hand, to the nearest region for regions that aren't 1:1. 
That's a different issue we will work into as part of implementing the redirecting.

**Comment by jaypipes** [comment]
The following regions should serve the image layers:

* us-west-2
* us-west-1
* us-east-1
* eu-central-1
* eu-central-1
* us-east-2
* ap-southeast-1
* us-west-1
* ap-northeast-1
* ap-south-1

Those 10 regions cover more than 90% of the source traffic for AWS customers pulling container images.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes-sigs/oci-proxy/issues/39 which seems to have wound up with most of the region selection discussion rather than this issue.
