### ISSUE TITLE
Privacy policy for registry.k8s.io ?

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/oci-proxy#62]
Just questioning the need of the privacy policy. From https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/oD9_Q8Q9AAAJ, we may have individuals using their personal IP address. 

`registry.k8s.io` currently runs on GCP infrastructure. This means all GCP services we use are covered by [Google privacy policy ](https://www.google.com/intl/en/policies/privacy/)

I took a quick look on what other projects are doing:
Golang: https://proxy.golang.org/privacy
Pypi: https://www.python.org/privacy/
Debian: https://www.debian.org/legal/privacy

/sig k8s-infra
/assign @dims
cc @BenTheElder @cblecker

Feel free to close if it's not needed.

**Comment by dims** [comment]
I really like the standalone https://proxy.golang.org/privacy

Looks like CNCF has one for the mailing lists - https://lists.cncf.io/static/privacy

**Comment by dims** [comment]
maven has one too https://repo1.maven.org/terms.html

**Comment by dims** [comment]
There is a LF level privacy policy - https://www.linuxfoundation.org/privacy-policy/

But not one at the CNCF level.

**Comment by dims** [comment]
xref: https://github.com/cncf/foundation/issues/337

**Comment by dims** [comment]
Question asked on slack here: https://cloud-native.slack.com/archives/C0MP69YF4/p1651348982279889

**Comment by dims** [comment]
Answer from @caniszczyk is to link to the LF Privacy Policy - https://www.linuxfoundation.org/privacy-policy/

**Comment by BenTheElder** [comment]
TODO (BenTheElder): update oci-proxy / archeio to serve a link to the LF privacy policy.

**Comment by BenTheElder** [comment]
I'm going to file a new issue to preserve the history here but track *Actually linking* the LF policy
