### ISSUE TITLE
workaround broken cloud run X-Forwarded-For header

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#63]
See details debugged in https://github.com/kubernetes-sigs/oci-proxy/pull/61#issuecomment-1105824535

/assign

been looking into the best forward plan for this, given it seems likely the bug will eventually be fixed.
will send a PR soonish hopefully.
/kind bug
/sig k8s-infra

**Comment by aojea** [comment]
but that are the consequences of the extra ip in the headers? is breaking the registry?

**Comment by BenTheElder** [comment]
if we detect the client is always the GCLB IP, then we will never direct to AWS 🙃

**Comment by dims** [comment]
LOL true dat Ben! :)

**Comment by BenTheElder** [comment]
this is working:
> "redirecting blob request to AWS" region="us-west-1" path="/v2/etcdadm/etcd-manager/blobs/sha256:f57d734dc10071966025291ffdbd1abfd0816c62e2ae9c5fb74efc025df6bcaa"
