### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#7]
We should enable CI to run roughly:
- `make verify`
- `make test`
- `make images build`
(each of these should probably be a distinct job in parallel)

We can probably use github actions or prow. `make verify` will require docker or the current shellcheck binary. the rest merely require bash/posix/make.

**Comment by BenTheElder** [comment]
CI jobs added, need to test them, then fix any issues, then make required.

**Comment by ameukam** [comment]
FWIW we already have shellcheckpresent in gcr.io/k8s-staging-infra-tools/k8s-infra:latest: https://github.com/kubernetes/k8s.io/blob/main/images/k8s-infra/Dockerfile#L38. (need to be updated)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/25047#issuecomment-1023949950

these are working good now, making them blocking in https://github.com/kubernetes/test-infra/pull/25049

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/oci-proxy/pull/12 you can see here that this is done, we have required presubmits covering all of these things since https://github.com/kubernetes/test-infra/pull/25049
