### ISSUE TITLE
Mapping AWS regions and S3 bucket region

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/oci-proxy#72]
Part of:
  - https://github.com/kubernetes/k8s.io/issues/3411
  
From https://github.com/kubernetes-sigs/oci-proxy/issues/39, we identified which region the traffic come the most but we need to ensure redirection for traffic coming from regions not listed. 
We could also assume the rest of regions are served from only 1 bucket but they is a risk of high latency during image pulling.

Draft:

| regions | bucket name | bucket location |
| -------- | -------- | -------- |
| us-east-1, sa-east-1     |      | us-east-1     |
| ca-central-1, us-east-2     |      | us-east-2     |
| us-west-1     |      | us-west-1     |
| us-west-2     |      | us-west-2     |
| ap-south-1, me-south-1     |      | ap-south-1    |
| ap-northeast-1, ap-northeast-2, ap-northeast-3     |      | ap-northeast-1 |
| ap-east-1, ap-southeast-1, ap-southeast-2. ap-southeast-3     |      | ap-southeast-1|
| eu-central-1, eu-south-1     |      | eu-central-1     |
| eu-west-1, af-south-1    |      | eu-west-1     |
| eu-north-1, eu-west-2, eu-west-3     |      | eu-west-2     |

/sig k8s-infra
/area artifacts
/priority important-soon
/milestone v1.25
/assign @BenTheElder

**Comment by BenTheElder** [comment]
cc @jaypipes 

> Not listed:
> ap-southeast-3
> ap-northeast-3
> ap-southeast-2
> sa-east-1

I would guess:
- ap-southeast-3 => ap-southeast-1
- ap-northeast-3 => ap-northeast-1
- ap-southeast-2 => ap-southeast-1
- sa-east-1 => us-east-1

**Comment by Riaankl** [comment]
> > cc @jaypipes
> > > Not listed:
> > > ap-southeast-3
> > > ap-northeast-3
> > > ap-southeast-2
> > > sa-east-1
> > 
> > 
> > I would guess:
> > ```
> > * ap-southeast-3 => ap-southeast-1
> > 
> > * ap-northeast-3 => ap-northeast-1
> > 
> > * ap-southeast-2 => ap-southeast-1
> > 
> > * sa-east-1 => us-east-1
> > ```
> 
> @BenTheElder yep, that works. +1
> 
> Keep in mind the amount of traffic coming from these regions is very low.

Looking at the Data Studio report all four regions <2% total

**Comment by BenTheElder** [comment]
So the remaining bit then is just mapping the regions to their bucket names, then we can update https://github.com/kubernetes-sigs/oci-proxy/blob/main/cmd/archeio/app/buckets.go

**Comment by BenTheElder** [comment]
[this issue is blocked on the buckets being up and ready, so don't jump into working on this one just yet]

**Comment by BenTheElder** [comment]
xref #76 the staging deployment should run in the same regions so we can get realistic latency results vs production and these buckets

**Comment by BenTheElder** [comment]
this was done in https://github.com/kubernetes-sigs/oci-proxy/pull/82
