### ISSUE TITLE
gate or temporarily compile out s3 redirect

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#80]
since the s3 buckets are still not ready, we should not block #77 rollout to registry.k8s.io on production s3 bucket availability.

I didn't think it would take this long, so I went with the simpler option of not gating s3 redirection / maintaining two modes, figuring we'd promote to production soon enough, and the initial production app is *literally* just bog simple 3XX to k8s.gcr.io so we can get users on registry.k8s.io and shouldn't need patches.

since it is taking a while, we should make it possible to continue iterating on other aspects, like redirecting to the individual GCR regions backing k8s.gcr.io ourselves, and later artifact registry instances instaed.

**Comment by BenTheElder** [comment]
Ordinarily for `help wanted` issues the author would probably help guide contributors, but I am going on vacation for a few weeks and will be relatively unavailable until sometime after July 25th.

`@ameukam` and `@dims` are repo approvers / admins and should be able to help in the meantime.

See also https://kubernetes.slack.com/archives/CCK68P2Q2/p1656629484801139?thread_ts=1656626472.238269&cid=CCK68P2Q2 in Kubernetes slack.

**Comment by BenTheElder** [comment]
alternatively if production buckets become ready, implement https://github.com/kubernetes-sigs/oci-proxy/issues/72 instead and then start looking at how e2e testing behaves. `@ameukam` or `@dims` can inspect the cloud run logs etc for request latency etc. once we have many regions.

**Comment by BobyMCbobs** [comment]
The buckets appear to be all manually synced now and #82 is in a good state.

Is feature gating still necessary?
