### ISSUE TITLE
serve privacy policy

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/oci-proxy#81]
We determined in #62 that we should be operating under the linux foundation privacy policy

However, archeio does not itself serve the privacy policy in any way.

We should add an endpoint for humans like `/privacy` (this is fine, registry API calls are all under `/v2/`) that redirects to the LF privacy page to start.

It might be worth considering a landing page with some context and a link to the LF page in the future instead.

**Comment by jeremyphua** [comment]
Hello! Is it alright if I take a look at this issue?

**Comment by ameukam** [comment]
/reopen

```bash
$curl -I https://registry-sandbox.k8s.io/privacy                                                                                                 03:07:57 PM
HTTP/2 307
content-type: text/html; charset=utf-8
location: https://www.linuxfoundation.org/privacy-policy/
x-cloud-trace-context: 816d27a964fc1f105f86488e460575b3;o=1
date: Mon, 04 Jul 2022 13:31:03 GMT
server: Google Frontend
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by BenTheElder** [comment]
@ameukam can you add more context why this is reopened and what next steps are?

**Comment by ameukam** [comment]
On a second thought, we can close this.
/close
