### ISSUE TITLE
Cut 0.0.2 release

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/oci-proxy#97]
We should cut a new tag for `archeio`. Lot of changes landed after the `0.0.1`

**Comment by ameukam** [comment]
I think what's remaining before we cut the tag is https://github.com/kubernetes-sigs/oci-proxy/issues/72

/assign @BenTheElder 
cc @dims

**Comment by BenTheElder** [comment]
#72 is done, just need to make a tag and push it, then promote the image

**Comment by ameukam** [comment]
Tag created: https://github.com/kubernetes-sigs/oci-proxy/releases/tag/v0.0.2

**Comment by ameukam** [comment]
Image matching the Github tag is promoted: https://github.com/kubernetes/k8s.io/pull/4117
/close
